
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


export const metadata = {
  title: "Poppins Website",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
   
      >
        {/* === Header === */}
        <Header />

        {/* === Page Content === */}
        <main >{children}</main>

        {/* === Footer === */}
        <Footer />
      </body>
    </html>
  );
}
