import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ReduxProvider from "./providers/ReduxProvider";
import GlobalSettingsLoader from "./components/GlobalSettingsLoader";
import CartPersistence from "./components/CartPersistence";

export const metadata = {
  title: "Popcon World - Worlds Largest Popcorn Store",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* === FONT LINK HERE === */}
        <link
          href="https://db.onlinewebfonts.com/c/25c5b8e8220ef701ff273edf38122499?family=LHF+Splash+Regular"
          rel="stylesheet"
          precedence="default"   // ✅ add this to fix warning
        />
      </head>
      <body>
        <ReduxProvider>
          <GlobalSettingsLoader />
          <CartPersistence />
          {/* === Header === */}
          <Header />

          {/* === Page Content === */}
          <main>{children}</main>

          {/* === Footer === */}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
